version: '3.7'
services:
  redis:
    image: redis
#    ports:
#      - 6379:6379
    volumes:
      - ./dump.rdb:/data/dump.rdb
  node:
    depends_on:
      - redis
    build: .
    working_dir: /usr/src/app
